/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laestanteria;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author a22davidma
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NMain
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean crearUsuario() {
        boolean toret = false;
        String nombre = campoNombre.getText();
        String dni = dniUsuario.getText();
        String correo = campoCorreo.getText();
        String contraUsuario = campoConteraseñaUsu.getText();
        String confirContraseña = campoConfirmarContraseña.getText();
        Cliente prueba = new Cliente(dni, nombre, correo, contraUsuario);
        Dao crearUsu = new Dao(dni, contraUsuario);

        if (crearUsu.crearUsuario(prueba)) {
            return true;
        }
        return toret;

    }

    private boolean comprobarUsuario() {
        boolean toret = false;
        Dao comprobar = new Dao();
        if (comprobar.comprobarUsuario(campoUsuario.getText(), campoContraseña.getText())) {
            toret = true;
            showMessage("USUARIO CORRECTO");
        } else {
            showMessage("USURIO NO ENCONTRADO, VUELVA A INTRODUCIR LOS VALORES");
        }
        return toret;
    }

    private void consultarAlmacenamiento() {
        boolean toret = false;
        Dao dao = new Dao();
        DefaultTableModel modelo = (DefaultTableModel) tablaAlmacenamiento.getModel();

        for (int i = 0; i < dao.productoPrecioAlmacenamiento(TipoProducto.almacenamiento).size(); i++) {
            modelo.addRow((Object[]) dao.productoPrecioAlmacenamiento(TipoProducto.almacenamiento).get(i));
        }

        tablaAlmacenamiento.setModel(modelo);

    }

    private void consultarTelefono() {
        Dao dao = new Dao();
        DefaultTableModel modelo = (DefaultTableModel) tablaTelefonos.getModel();
        for (int i = 0; i < dao.productoTelefonos(TipoProducto.telefonos).size(); i++) {
            modelo.addRow((Object[]) dao.productoTelefonos(TipoProducto.telefonos).get(i));
        }
        tablaTelefonos.setModel(modelo);
    }
    
    private void consultarComponentes(){
        Dao dao = new Dao();
        DefaultTableModel modelo = (DefaultTableModel) tablaComponentes.getModel();
        for (int i = 0; i < dao.productosComponentes(TipoProducto.componentes).size(); i++) {
            modelo.addRow((Object[])dao.productosComponentes(TipoProducto.pc).get(i));
        }
        tablaTelefonos.setModel(modelo);
    }
    
    private void consultarPc(){
        
    }

    private void showError(String text) {
        JOptionPane.showMessageDialog(this, text, "error", JOptionPane.ERROR_MESSAGE);
    }

    private void showMessage(String text) {
        JOptionPane.showMessageDialog(this, text, "information", JOptionPane.INFORMATION_MESSAGE);
    }

    @SuppressWarnings("unchecked")

    private void cambiarPanel(String nomeTarxeta) {
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, nomeTarxeta);
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        campoContraseña = new javax.swing.JTextField();
        botonLogin = new javax.swing.JButton();
        crearCuentaPanel = new javax.swing.JPanel();
        correoUsu = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        nombreUsu = new javax.swing.JLabel();
        confirmarContraseña = new javax.swing.JLabel();
        contraseñaUsu = new javax.swing.JLabel();
        campoConfirmarContraseña = new javax.swing.JPasswordField();
        campoConteraseñaUsu = new javax.swing.JPasswordField();
        botonCrearCuenta = new javax.swing.JButton();
        labelDni = new javax.swing.JLabel();
        dniUsuario = new javax.swing.JTextField();
        menuPrincipal = new javax.swing.JPanel();
        catalogoButton = new javax.swing.JButton();
        historialButton = new javax.swing.JButton();
        cuentaButton = new javax.swing.JButton();
        pagosButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cuentaPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        nombreUsuPanel = new javax.swing.JLabel();
        saldoPanel = new javax.swing.JLabel();
        dniPanel = new javax.swing.JLabel();
        gmailPanel = new javax.swing.JLabel();
        volverButton01 = new javax.swing.JButton();
        historialPagosButton = new javax.swing.JButton();
        obtenerGmail = new javax.swing.JTextField();
        obtenerNombre = new javax.swing.JTextField();
        obtenerDni = new javax.swing.JTextField();
        obtenerSaldo = new javax.swing.JTextField();
        historialPagosPanel = new javax.swing.JPanel();
        pagosTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        volverButton02 = new javax.swing.JButton();
        catalogoPanel = new javax.swing.JPanel();
        catalogoLabel = new javax.swing.JLabel();
        componentesPcButton = new javax.swing.JButton();
        volverButton03 = new javax.swing.JButton();
        celularesButton = new javax.swing.JButton();
        accesoriosButton = new javax.swing.JButton();
        almacenamientoButton = new javax.swing.JButton();
        pcButton = new javax.swing.JButton();
        celularesPanel = new javax.swing.JPanel();
        celularLista = new javax.swing.JScrollPane();
        tablaTelefonos = new javax.swing.JTable();
        infoCelularesButton = new javax.swing.JButton();
        volverButton04 = new javax.swing.JButton();
        accesoriosPanel = new javax.swing.JPanel();
        accesorioLista = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        infoAccesoriosButton = new javax.swing.JButton();
        volverButton05 = new javax.swing.JButton();
        almacenamientoPanel = new javax.swing.JPanel();
        almacenamientoLista = new javax.swing.JScrollPane();
        tablaAlmacenamiento = new javax.swing.JTable();
        infoAlmacenamientoButton = new javax.swing.JButton();
        volverButton06 = new javax.swing.JButton();
        pcPanel = new javax.swing.JPanel();
        pcLista = new javax.swing.JScrollPane();
        tablaPC = new javax.swing.JTable();
        infoPcButton = new javax.swing.JButton();
        volverButton07 = new javax.swing.JButton();
        componentesPcPanel = new javax.swing.JPanel();
        componentesPcLista = new javax.swing.JScrollPane();
        tablaComponentes = new javax.swing.JTable();
        infoComponentesPcButton = new javax.swing.JButton();
        volverButton08 = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        añadirLabel = new javax.swing.JLabel();
        botonAñadir = new javax.swing.JButton();
        volverButton09 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pedidosTable = new javax.swing.JTable();
        pedidosLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        accesoPrograma = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        crearCuenta = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        usuario.setText("Usuario");

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        contraseña.setText("Contraseña");

        botonLogin.setText("Enviar");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contraseña)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(botonLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña)
                    .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(botonLogin)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        mainPanel.add(loginPanel, "loginPanel");

        correoUsu.setText("Correo");

        nombreUsu.setText("Nombre de Usuario");

        confirmarContraseña.setText("Confirmar Contraseña");

        contraseñaUsu.setText("Contraseña");

        botonCrearCuenta.setText("Crear Cuenta");
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });

        labelDni.setText("Dni");

        dniUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crearCuentaPanelLayout = new javax.swing.GroupLayout(crearCuentaPanel);
        crearCuentaPanel.setLayout(crearCuentaPanelLayout);
        crearCuentaPanelLayout.setHorizontalGroup(
            crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCuentaPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correoUsu)
                    .addComponent(confirmarContraseña)
                    .addComponent(contraseñaUsu)
                    .addComponent(nombreUsu)
                    .addComponent(labelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCrearCuenta)
                    .addComponent(campoCorreo)
                    .addComponent(campoNombre)
                    .addComponent(campoConfirmarContraseña)
                    .addComponent(campoConteraseñaUsu)
                    .addComponent(dniUsuario))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        crearCuentaPanelLayout.setVerticalGroup(
            crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCuentaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDni))
                .addGap(13, 13, 13)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConteraseñaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonCrearCuenta)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mainPanel.add(crearCuentaPanel, "crearCuentaPanel");

        catalogoButton.setText("Catálogo");
        catalogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoButtonActionPerformed(evt);
            }
        });

        historialButton.setText("Historial");
        historialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialButtonActionPerformed(evt);
            }
        });

        cuentaButton.setText("Cuenta");
        cuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaButtonActionPerformed(evt);
            }
        });

        pagosButton.setText("Pagos");
        pagosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagosButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Cesta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPrincipalLayout = new javax.swing.GroupLayout(menuPrincipal);
        menuPrincipal.setLayout(menuPrincipalLayout);
        menuPrincipalLayout.setHorizontalGroup(
            menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catalogoButton)
                    .addComponent(historialButton))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuentaButton)
                    .addComponent(pagosButton))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        menuPrincipalLayout.setVerticalGroup(
            menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catalogoButton)
                    .addComponent(pagosButton)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historialButton)
                    .addComponent(cuentaButton))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        mainPanel.add(menuPrincipal, "menuPanel");

        infoLabel.setText("Información de la cuenta");

        nombreUsuPanel.setText("Nombre de usuario");

        saldoPanel.setText("Saldo");

        dniPanel.setText("Dni");

        gmailPanel.setText("Gmail");

        volverButton01.setText("Volver");
        volverButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton01ActionPerformed(evt);
            }
        });

        historialPagosButton.setText("Historial de Pagos");
        historialPagosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialPagosButtonActionPerformed(evt);
            }
        });

        obtenerGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerGmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuentaPanelLayout = new javax.swing.GroupLayout(cuentaPanel);
        cuentaPanel.setLayout(cuentaPanelLayout);
        cuentaPanelLayout.setHorizontalGroup(
            cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentaPanelLayout.createSequentialGroup()
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuentaPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(infoLabel))
                    .addGroup(cuentaPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cuentaPanelLayout.createSequentialGroup()
                                .addComponent(historialPagosButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(volverButton01))
                            .addGroup(cuentaPanelLayout.createSequentialGroup()
                                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gmailPanel)
                                    .addComponent(nombreUsuPanel))
                                .addGap(92, 92, 92)
                                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(obtenerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obtenerGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(cuentaPanelLayout.createSequentialGroup()
                                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saldoPanel)
                                    .addComponent(dniPanel))
                                .addGap(167, 167, 167)
                                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(obtenerDni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obtenerSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(65, 65, 65))
        );
        cuentaPanelLayout.setVerticalGroup(
            cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addGap(25, 25, 25)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cuentaPanelLayout.createSequentialGroup()
                        .addComponent(nombreUsuPanel)
                        .addGap(18, 18, 18)
                        .addComponent(gmailPanel))
                    .addGroup(cuentaPanelLayout.createSequentialGroup()
                        .addComponent(obtenerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obtenerGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniPanel)
                    .addComponent(obtenerDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoPanel)
                    .addComponent(obtenerSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverButton01)
                    .addComponent(historialPagosButton))
                .addGap(34, 34, 34))
        );

        mainPanel.add(cuentaPanel, "cuentaPanel");

        historialPagosPanel.setPreferredSize(new java.awt.Dimension(400, 277));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pago", "Fecha", "Datos"
            }
        ));
        pagosTable.setViewportView(jTable1);

        volverButton02.setText("Volver");
        volverButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout historialPagosPanelLayout = new javax.swing.GroupLayout(historialPagosPanel);
        historialPagosPanel.setLayout(historialPagosPanelLayout);
        historialPagosPanelLayout.setHorizontalGroup(
            historialPagosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialPagosPanelLayout.createSequentialGroup()
                .addGroup(historialPagosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(historialPagosPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pagosTable, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(historialPagosPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(volverButton02)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        historialPagosPanelLayout.setVerticalGroup(
            historialPagosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historialPagosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pagosTable, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(volverButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        mainPanel.add(historialPagosPanel, "historialPagosPanel");

        catalogoLabel.setText("Catálogo");

        componentesPcButton.setText("Componentes Pc");
        componentesPcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componentesPcButtonActionPerformed(evt);
            }
        });

        volverButton03.setText("Volver");
        volverButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton03ActionPerformed(evt);
            }
        });

        celularesButton.setText("Celulares");
        celularesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularesButtonActionPerformed(evt);
            }
        });

        accesoriosButton.setText("Accesorios");
        accesoriosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoriosButtonActionPerformed(evt);
            }
        });

        almacenamientoButton.setText("Almacenamiento");
        almacenamientoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenamientoButtonActionPerformed(evt);
            }
        });

        pcButton.setText("Pc");
        pcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout catalogoPanelLayout = new javax.swing.GroupLayout(catalogoPanel);
        catalogoPanel.setLayout(catalogoPanelLayout);
        catalogoPanelLayout.setHorizontalGroup(
            catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoPanelLayout.createSequentialGroup()
                .addGroup(catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(catalogoPanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(catalogoLabel))
                    .addGroup(catalogoPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celularesButton)
                            .addComponent(pcButton))
                        .addGap(26, 26, 26)
                        .addGroup(catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(componentesPcButton)
                            .addGroup(catalogoPanelLayout.createSequentialGroup()
                                .addComponent(accesoriosButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(almacenamientoButton)))))
                .addGap(21, 21, 21))
            .addGroup(catalogoPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(volverButton03)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catalogoPanelLayout.setVerticalGroup(
            catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(catalogoLabel)
                .addGap(67, 67, 67)
                .addGroup(catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularesButton)
                    .addComponent(accesoriosButton)
                    .addComponent(almacenamientoButton))
                .addGap(32, 32, 32)
                .addGroup(catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(componentesPcButton)
                    .addComponent(pcButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(volverButton03)
                .addGap(27, 27, 27))
        );

        mainPanel.add(catalogoPanel, "catalogoPanel");

        tablaTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Celular", "Precio"
            }
        ));
        celularLista.setViewportView(tablaTelefonos);

        infoCelularesButton.setText("Info");
        infoCelularesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoCelularesButtonActionPerformed(evt);
            }
        });

        volverButton04.setText("Volver");
        volverButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton04ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout celularesPanelLayout = new javax.swing.GroupLayout(celularesPanel);
        celularesPanel.setLayout(celularesPanelLayout);
        celularesPanelLayout.setHorizontalGroup(
            celularesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(celularesPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(celularLista, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(celularesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoCelularesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton04))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        celularesPanelLayout.setVerticalGroup(
            celularesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, celularesPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(celularLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(celularesPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(infoCelularesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton04)
                .addGap(47, 47, 47))
        );

        mainPanel.add(celularesPanel, "celularesPanel");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Accesorio", "Precio"
            }
        ));
        accesorioLista.setViewportView(jTable3);

        infoAccesoriosButton.setText("Info");
        infoAccesoriosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoAccesoriosButtonActionPerformed(evt);
            }
        });

        volverButton05.setText("Volver");
        volverButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton05ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accesoriosPanelLayout = new javax.swing.GroupLayout(accesoriosPanel);
        accesoriosPanel.setLayout(accesoriosPanelLayout);
        accesoriosPanelLayout.setHorizontalGroup(
            accesoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accesoriosPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(accesorioLista, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(accesoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoAccesoriosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton05))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        accesoriosPanelLayout.setVerticalGroup(
            accesoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accesoriosPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(accesorioLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(accesoriosPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(infoAccesoriosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton05)
                .addGap(47, 47, 47))
        );

        mainPanel.add(accesoriosPanel, "accesoriosPanel");

        tablaAlmacenamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Almacenamiento", "Precio"
            }
        ));
        almacenamientoLista.setViewportView(tablaAlmacenamiento);

        infoAlmacenamientoButton.setText("Info");
        infoAlmacenamientoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoAlmacenamientoButtonActionPerformed(evt);
            }
        });

        volverButton06.setText("Volver");
        volverButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton06ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout almacenamientoPanelLayout = new javax.swing.GroupLayout(almacenamientoPanel);
        almacenamientoPanel.setLayout(almacenamientoPanelLayout);
        almacenamientoPanelLayout.setHorizontalGroup(
            almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenamientoPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(almacenamientoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoAlmacenamientoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton06))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        almacenamientoPanelLayout.setVerticalGroup(
            almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, almacenamientoPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(almacenamientoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(almacenamientoPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(infoAlmacenamientoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton06)
                .addGap(47, 47, 47))
        );

        mainPanel.add(almacenamientoPanel, "almacenamientoPanel");

        tablaPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pc", "Precio"
            }
        ));
        pcLista.setViewportView(tablaPC);

        infoPcButton.setText("Info");
        infoPcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoPcButtonActionPerformed(evt);
            }
        });

        volverButton07.setText("Volver");
        volverButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton07ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pcPanelLayout = new javax.swing.GroupLayout(pcPanel);
        pcPanel.setLayout(pcPanelLayout);
        pcPanelLayout.setHorizontalGroup(
            pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pcLista, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton07))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pcPanelLayout.setVerticalGroup(
            pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pcPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(pcLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(pcPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(infoPcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton07)
                .addGap(47, 47, 47))
        );

        mainPanel.add(pcPanel, "pcPanel");

        tablaComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Componente", "Precio"
            }
        ));
        componentesPcLista.setViewportView(tablaComponentes);

        infoComponentesPcButton.setText("Info");
        infoComponentesPcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoComponentesPcButtonActionPerformed(evt);
            }
        });

        volverButton08.setText("Volver");
        volverButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton08ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout componentesPcPanelLayout = new javax.swing.GroupLayout(componentesPcPanel);
        componentesPcPanel.setLayout(componentesPcPanelLayout);
        componentesPcPanelLayout.setHorizontalGroup(
            componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentesPcPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(componentesPcLista, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoComponentesPcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton08))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        componentesPcPanelLayout.setVerticalGroup(
            componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, componentesPcPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(componentesPcLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(componentesPcPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(infoComponentesPcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton08)
                .addGap(47, 47, 47))
        );

        mainPanel.add(componentesPcPanel, "componentesPcPanel");

        añadirLabel.setText("Info de producto");

        botonAñadir.setText("Añadir a cesta");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });

        volverButton09.setText("Volver");
        volverButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton09ActionPerformed(evt);
            }
        });

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable7);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton09)
                .addGap(31, 31, 31))
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(añadirLabel))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(añadirLabel)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAñadir)
                    .addComponent(volverButton09))
                .addGap(15, 15, 15))
        );

        mainPanel.add(infoPanel, "infoPanel");

        pedidosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id ", "Info "
            }
        ));
        jScrollPane2.setViewportView(pedidosTable);

        pedidosLabel.setText("Historial de Pedidos");

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(pedidosLabel)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(pedidosLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(56, 56, 56))))
        );

        mainPanel.add(jPanel1, "historialCuentaPanel");

        accesoPrograma.setText("Acceso");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        accesoPrograma.add(login);

        crearCuenta.setText("Crear cuenta");
        crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaActionPerformed(evt);
            }
        });
        accesoPrograma.add(crearCuenta);

        jMenuItem1.setText("Main");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        accesoPrograma.add(jMenuItem1);

        jMenuBar1.add(accesoPrograma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        cambiarPanel("loginPanel");
    }//GEN-LAST:event_loginActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void dniUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniUsuarioActionPerformed

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        if (campoConteraseñaUsu.getText().equals(campoConfirmarContraseña.getText())) {

            if (crearUsuario()) {
                showMessage("Usuario creado :)");
                cambiarPanel("menuPanel");
            } else {
                showMessage("USUARIO YA EXISTE");
            }
        } else {
            showError("La contraseña no coincide");
        }
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    private void crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaActionPerformed
        cambiarPanel("crearCuentaPanel");


    }//GEN-LAST:event_crearCuentaActionPerformed

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed

        if (comprobarUsuario()) {
            cambiarPanel("menuPanel");
        }

    }//GEN-LAST:event_botonLoginActionPerformed

    private void componentesPcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componentesPcButtonActionPerformed
        cambiarPanel("componentesPcPanel");
        consultarComponentes();
    }//GEN-LAST:event_componentesPcButtonActionPerformed

    private void volverButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton04ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton04ActionPerformed

    private void volverButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton05ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton05ActionPerformed

    private void volverButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton06ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton06ActionPerformed

    private void volverButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton07ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton07ActionPerformed

    private void volverButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton08ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton08ActionPerformed

    private void volverButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton03ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_volverButton03ActionPerformed

    private void catalogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoButtonActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_catalogoButtonActionPerformed

    private void historialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialButtonActionPerformed
        cambiarPanel("historialCuentaPanel");
    }//GEN-LAST:event_historialButtonActionPerformed

    private void cuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaButtonActionPerformed
        cambiarPanel("cuentaPanel");
    }//GEN-LAST:event_cuentaButtonActionPerformed

    private void pagosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagosButtonActionPerformed
        cambiarPanel("pagosPanel");
    }//GEN-LAST:event_pagosButtonActionPerformed

    private void volverButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton01ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_volverButton01ActionPerformed

    private void historialPagosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialPagosButtonActionPerformed
        cambiarPanel("historialPagosPanel");
    }//GEN-LAST:event_historialPagosButtonActionPerformed

    private void volverButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton02ActionPerformed
        cambiarPanel("cuentaPanel");


    }//GEN-LAST:event_volverButton02ActionPerformed

    private void celularesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularesButtonActionPerformed
        cambiarPanel("celularesPanel");
        consultarTelefono();
    }//GEN-LAST:event_celularesButtonActionPerformed

    private void accesoriosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoriosButtonActionPerformed
        cambiarPanel("accesoriosPanel");
    }//GEN-LAST:event_accesoriosButtonActionPerformed

    private void almacenamientoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenamientoButtonActionPerformed

        cambiarPanel("almacenamientoPanel");

        consultarAlmacenamiento();

    }//GEN-LAST:event_almacenamientoButtonActionPerformed

    private void pcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcButtonActionPerformed
        cambiarPanel("pcPanel");
    }//GEN-LAST:event_pcButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cambiarPanel("pcPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void volverButton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton09ActionPerformed
        cambiarPanel("pcPanel");
    }//GEN-LAST:event_volverButton09ActionPerformed

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAñadirActionPerformed

    private void obtenerGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtenerGmailActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void infoCelularesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoCelularesButtonActionPerformed
        cambiarPanel("infoPanel");
    }//GEN-LAST:event_infoCelularesButtonActionPerformed

    private void infoAccesoriosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoAccesoriosButtonActionPerformed
        cambiarPanel("infoPanel");
    }//GEN-LAST:event_infoAccesoriosButtonActionPerformed

    private void infoAlmacenamientoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoAlmacenamientoButtonActionPerformed
        cambiarPanel("infoPanel");
    }//GEN-LAST:event_infoAlmacenamientoButtonActionPerformed

    private void infoPcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoPcButtonActionPerformed
        cambiarPanel("infoPanel");
    }//GEN-LAST:event_infoPcButtonActionPerformed

    private void infoComponentesPcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoComponentesPcButtonActionPerformed
        cambiarPanel("infoPanel");
    }//GEN-LAST:event_infoComponentesPcButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accesoPrograma;
    private javax.swing.JScrollPane accesorioLista;
    private javax.swing.JButton accesoriosButton;
    private javax.swing.JPanel accesoriosPanel;
    private javax.swing.JButton almacenamientoButton;
    private javax.swing.JScrollPane almacenamientoLista;
    private javax.swing.JPanel almacenamientoPanel;
    private javax.swing.JLabel añadirLabel;
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton botonLogin;
    private javax.swing.JPasswordField campoConfirmarContraseña;
    private javax.swing.JPasswordField campoConteraseñaUsu;
    private javax.swing.JTextField campoContraseña;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JButton catalogoButton;
    private javax.swing.JLabel catalogoLabel;
    private javax.swing.JPanel catalogoPanel;
    private javax.swing.JScrollPane celularLista;
    private javax.swing.JButton celularesButton;
    private javax.swing.JPanel celularesPanel;
    private javax.swing.JButton componentesPcButton;
    private javax.swing.JScrollPane componentesPcLista;
    private javax.swing.JPanel componentesPcPanel;
    private javax.swing.JLabel confirmarContraseña;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel contraseñaUsu;
    private javax.swing.JLabel correoUsu;
    private javax.swing.JMenuItem crearCuenta;
    private javax.swing.JPanel crearCuentaPanel;
    private javax.swing.JButton cuentaButton;
    private javax.swing.JPanel cuentaPanel;
    private javax.swing.JLabel dniPanel;
    private javax.swing.JTextField dniUsuario;
    private javax.swing.JLabel gmailPanel;
    private javax.swing.JButton historialButton;
    private javax.swing.JButton historialPagosButton;
    private javax.swing.JPanel historialPagosPanel;
    private javax.swing.JButton infoAccesoriosButton;
    private javax.swing.JButton infoAlmacenamientoButton;
    private javax.swing.JButton infoCelularesButton;
    private javax.swing.JButton infoComponentesPcButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton infoPcButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable7;
    private javax.swing.JLabel labelDni;
    private javax.swing.JMenuItem login;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPrincipal;
    private javax.swing.JLabel nombreUsu;
    private javax.swing.JLabel nombreUsuPanel;
    private javax.swing.JTextField obtenerDni;
    private javax.swing.JTextField obtenerGmail;
    private javax.swing.JTextField obtenerNombre;
    private javax.swing.JTextField obtenerSaldo;
    private javax.swing.JButton pagosButton;
    private javax.swing.JScrollPane pagosTable;
    private javax.swing.JButton pcButton;
    private javax.swing.JScrollPane pcLista;
    private javax.swing.JPanel pcPanel;
    private javax.swing.JLabel pedidosLabel;
    private javax.swing.JTable pedidosTable;
    private javax.swing.JLabel saldoPanel;
    private javax.swing.JTable tablaAlmacenamiento;
    private javax.swing.JTable tablaComponentes;
    private javax.swing.JTable tablaPC;
    private javax.swing.JTable tablaTelefonos;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton volverButton01;
    private javax.swing.JButton volverButton02;
    private javax.swing.JButton volverButton03;
    private javax.swing.JButton volverButton04;
    private javax.swing.JButton volverButton05;
    private javax.swing.JButton volverButton06;
    private javax.swing.JButton volverButton07;
    private javax.swing.JButton volverButton08;
    private javax.swing.JButton volverButton09;
    // End of variables declaration//GEN-END:variables
}
