/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laestanteria;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author a22davidma
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NMain
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean crearUsuario() {
        boolean toret = false;
        String nombre = campoNombre.getText();
        String dni = dniUsuario.getText();
        String correo = campoCorreo.getText();
        String contraUsuario = campoConteraseñaUsu.getText();
        String confirContraseña = campoConfirmarContraseña.getText();
        Cliente prueba = new Cliente(dni, nombre, correo, contraUsuario);
        Dao crearUsu = new Dao();

        if (crearUsu.crearUsuario(prueba)) {
            return true;
        }
        return toret;

    }

    private boolean comprobarUsuario() {
        boolean toret = false;
        Dao comprobar = new Dao();
        if (comprobar.comprobarUsuario(campoUsuario.getText(), campoContraseña.getText())) {
            toret = true;
            showMessage("USUARIO CORRECTO");
        } else {
            showMessage("USURIO NO ENCONTRADO, VUELVA A INTRODUCIR LOS VALORES");
        }
        return toret;
    }

    private void consultarAlmacenamiento() {
        boolean toret = false;
        Dao dao = new Dao();
        tablaAlmacenamiento.setRowSelectionAllowed(true);
        DefaultTableModel modelo = (DefaultTableModel) tablaAlmacenamiento.getModel();
         int [] filasSeleccionadas = tablaAlmacenamiento.getSelectedRows();
         
        for (int i = 0; i < filasSeleccionadas.length; i++) {
            modelo.removeRow(filasSeleccionadas[i]);
        }
        
        tablaAlmacenamiento.repaint();
        for (int i = 0; i < dao.productosComponentes(TipoProducto.almacenamiento).size(); i++) {
            modelo.addRow((Object[]) dao.productosComponentes(TipoProducto.almacenamiento).get(i));
        }

        tablaAlmacenamiento.setModel(modelo);

    }

    private void consultarTelefono() {
        Dao dao = new Dao();
        DefaultTableModel modelo = (DefaultTableModel) tablaTelefonos.getModel();
        for (int i = 0; i < dao.productosComponentes(TipoProducto.telefonos).size(); i++) {
            modelo.addRow((Object[]) dao.productosComponentes(TipoProducto.telefonos).get(i));
        }
        tablaTelefonos.setModel(modelo);
    }

    private void consultarComponentes() {
        Dao dao = new Dao();
        DefaultTableModel modelo = (DefaultTableModel) tablaComponentes.getModel();
        for (int i = 0; i < dao.productosComponentes(TipoProducto.componentes).size(); i++) {
            modelo.addRow((Object[]) dao.productosComponentes(TipoProducto.componentes).get(i));
        }
        tablaComponentes.setModel(modelo);
    }

    private void consultarPc() {
        Dao dao = new Dao();
        DefaultTableModel modelo = (DefaultTableModel) tablaPC.getModel();
        for (int i = 0; i < dao.productosComponentes(TipoProducto.pc).size(); i++) {
            modelo.addRow((Object[]) dao.productosComponentes(TipoProducto.pc).get(i));
        }
        tablaPC.setModel(modelo);

    }

    private void consultarPedidoUsuario() {
        Dao dao = new Dao();
        DefaultTableModel modelo = (DefaultTableModel) pedidosTable.getModel();
        if (campoNombre.getText().length() > 0) {
            for (int i = 0; i < dao.consultarPedidos(campoNombre.getText()).size(); i++) {
                modelo.addRow((Object[]) dao.consultarPedidos(campoNombre.getText()).get(i));
            }
        } else {
            for (int i = 0; i < dao.consultarPedidos(campoUsuario.getText()).size(); i++) {
                modelo.addRow((Object[]) dao.consultarPedidos(campoUsuario.getText()).get(i));
            }
        }

        pedidosTable.setModel(modelo);
    }

    private void infoUsuario() {
        Dao dao = new Dao();

        if (campoNombre.getText().length() > 0) {
            obtenerNombre.setText(dao.infoCuenta(campoNombre.getText())[0]);
            obtenerGmail.setText(dao.infoCuenta(campoNombre.getText())[1]);
            obtenerDni.setText(dao.infoCuenta(campoNombre.getText())[2]);
        } else {
            obtenerNombre.setText(dao.infoCuenta(campoUsuario.getText())[0]);
            obtenerGmail.setText(dao.infoCuenta(campoUsuario.getText())[1]);
            obtenerDni.setText(dao.infoCuenta(campoUsuario.getText())[2]);
        }

    }

    private void showError(String text) {
        JOptionPane.showMessageDialog(this, text, "error", JOptionPane.ERROR_MESSAGE);
    }

    private void showMessage(String text) {
        JOptionPane.showMessageDialog(this, text, "information", JOptionPane.INFORMATION_MESSAGE);
    }

    @SuppressWarnings("unchecked")

    private void cambiarPanel(String nomeTarxeta) {
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, nomeTarxeta);
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        botonLogin = new javax.swing.JButton();
        campoContraseña = new javax.swing.JPasswordField();
        logInLabel = new javax.swing.JLabel();
        crearCuentaPanel = new javax.swing.JPanel();
        correoUsu = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        nombreUsu = new javax.swing.JLabel();
        confirmarContraseña = new javax.swing.JLabel();
        contraseñaUsu = new javax.swing.JLabel();
        campoConfirmarContraseña = new javax.swing.JPasswordField();
        campoConteraseñaUsu = new javax.swing.JPasswordField();
        botonCrearCuenta = new javax.swing.JButton();
        labelDni = new javax.swing.JLabel();
        dniUsuario = new javax.swing.JTextField();
        signInLabel = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JPanel();
        catalogoButton = new javax.swing.JButton();
        historialButton = new javax.swing.JButton();
        cuentaButton = new javax.swing.JButton();
        pedidosButton = new javax.swing.JButton();
        cestaButton = new javax.swing.JButton();
        cuentaPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        nombreUsuPanel = new javax.swing.JLabel();
        dniPanel = new javax.swing.JLabel();
        gmailPanel = new javax.swing.JLabel();
        volverButton01 = new javax.swing.JButton();
        historialPagosButton = new javax.swing.JButton();
        obtenerGmail = new javax.swing.JTextField();
        obtenerNombre = new javax.swing.JTextField();
        obtenerDni = new javax.swing.JTextField();
        historialPagosPanel = new javax.swing.JPanel();
        pagosTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        volverButton02 = new javax.swing.JButton();
        historialPagosLabel = new javax.swing.JLabel();
        catalogoPanel = new javax.swing.JPanel();
        catalogoLabel = new javax.swing.JLabel();
        componentesPcButton = new javax.swing.JButton();
        volverButton03 = new javax.swing.JButton();
        celularesButton = new javax.swing.JButton();
        almacenamientoButton = new javax.swing.JButton();
        pcButton = new javax.swing.JButton();
        celularesPanel = new javax.swing.JPanel();
        celularLista = new javax.swing.JScrollPane();
        tablaTelefonos = new javax.swing.JTable();
        volverButton04 = new javax.swing.JButton();
        celularesLabel = new javax.swing.JLabel();
        añadirCestaButton01 = new javax.swing.JButton();
        celularBuscadorLabel = new javax.swing.JLabel();
        celularBuscadorText = new javax.swing.JTextField();
        almacenamientoPanel = new javax.swing.JPanel();
        almacenamientoLista = new javax.swing.JScrollPane();
        tablaAlmacenamiento = new javax.swing.JTable();
        volverButton06 = new javax.swing.JButton();
        almacenamientoLabel = new javax.swing.JLabel();
        buscadorAlmacenamientoLabel = new javax.swing.JLabel();
        almacenamientoBuscadorText = new javax.swing.JTextField();
        añadirCestaButton02 = new javax.swing.JButton();
        pcPanel = new javax.swing.JPanel();
        pcLista = new javax.swing.JScrollPane();
        tablaPC = new javax.swing.JTable();
        volverButton07 = new javax.swing.JButton();
        pcLabel = new javax.swing.JLabel();
        pcBuscadorLabel = new javax.swing.JLabel();
        pcBuscadorText = new javax.swing.JTextField();
        añadirCestaButton03 = new javax.swing.JButton();
        componentesPcPanel = new javax.swing.JPanel();
        componentesPcLista = new javax.swing.JScrollPane();
        tablaComponentes = new javax.swing.JTable();
        volverButton08 = new javax.swing.JButton();
        hardwareLabel = new javax.swing.JLabel();
        hardwareBuscadorLabel = new javax.swing.JLabel();
        hardwareBuscadorText = new javax.swing.JTextField();
        añadirCestaButton04 = new javax.swing.JButton();
        historialPedidosPanel = new javax.swing.JPanel();
        historialPedidosTable = new javax.swing.JScrollPane();
        pedidosTable = new javax.swing.JTable();
        historialPedidosLabel = new javax.swing.JLabel();
        volverButton10 = new javax.swing.JButton();
        cestaPanel = new javax.swing.JPanel();
        cestaLabel = new javax.swing.JLabel();
        cestaTable = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        volverButton11 = new javax.swing.JButton();
        pedidosPanel = new javax.swing.JPanel();
        pedidoTable = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        volverButton12 = new javax.swing.JButton();
        pedidosLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        accesoPrograma = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        crearCuenta = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        usuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usuario.setText("Usuario");

        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        contraseña.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contraseña.setText("Contraseña");

        botonLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonLogin.setText("Enviar");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        logInLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        logInLabel.setText("LOG IN:");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoContraseña)
                            .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(logInLabel))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(botonLogin)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(logInLabel)
                .addGap(29, 29, 29)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(botonLogin)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        mainPanel.add(loginPanel, "loginPanel");

        correoUsu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        correoUsu.setText("Correo");

        nombreUsu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombreUsu.setText("Nombre de Usuario");

        confirmarContraseña.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        confirmarContraseña.setText("Confirmar Contraseña");

        contraseñaUsu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contraseñaUsu.setText("Contraseña");

        botonCrearCuenta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonCrearCuenta.setText("Crear Cuenta");
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });

        labelDni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelDni.setText("Dni");

        dniUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniUsuarioActionPerformed(evt);
            }
        });

        signInLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        signInLabel.setText("SIGN IN:");

        javax.swing.GroupLayout crearCuentaPanelLayout = new javax.swing.GroupLayout(crearCuentaPanel);
        crearCuentaPanel.setLayout(crearCuentaPanelLayout);
        crearCuentaPanelLayout.setHorizontalGroup(
            crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCuentaPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearCuentaPanelLayout.createSequentialGroup()
                        .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correoUsu)
                            .addComponent(confirmarContraseña)
                            .addComponent(contraseñaUsu)
                            .addComponent(nombreUsu)
                            .addComponent(labelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoCorreo)
                            .addComponent(campoNombre)
                            .addComponent(campoConfirmarContraseña)
                            .addComponent(campoConteraseñaUsu)
                            .addComponent(dniUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crearCuentaPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(signInLabel))
                    .addGroup(crearCuentaPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(botonCrearCuenta)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        crearCuentaPanelLayout.setVerticalGroup(
            crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCuentaPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(signInLabel)
                .addGap(18, 18, 18)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDni))
                .addGap(13, 13, 13)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseñaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConteraseñaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearCuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(botonCrearCuenta)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        mainPanel.add(crearCuentaPanel, "crearCuentaPanel");

        catalogoButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        catalogoButton.setText("Catálogo");
        catalogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoButtonActionPerformed(evt);
            }
        });

        historialButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        historialButton.setText("Historial");
        historialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialButtonActionPerformed(evt);
            }
        });

        cuentaButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cuentaButton.setText("Cuenta");
        cuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaButtonActionPerformed(evt);
            }
        });

        pedidosButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pedidosButton.setText("Pedidos");
        pedidosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosButtonActionPerformed(evt);
            }
        });

        cestaButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cestaButton.setText("Cesta");
        cestaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cestaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPrincipalLayout = new javax.swing.GroupLayout(menuPrincipal);
        menuPrincipal.setLayout(menuPrincipalLayout);
        menuPrincipalLayout.setHorizontalGroup(
            menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cuentaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(catalogoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cestaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(historialButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedidosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        menuPrincipalLayout.setVerticalGroup(
            menuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPrincipalLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(catalogoButton)
                .addGap(36, 36, 36)
                .addComponent(cestaButton)
                .addGap(18, 18, 18)
                .addComponent(pedidosButton)
                .addGap(18, 18, 18)
                .addComponent(historialButton)
                .addGap(18, 18, 18)
                .addComponent(cuentaButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        mainPanel.add(menuPrincipal, "menuPanel");

        infoLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        infoLabel.setText("Información De La Cuenta");

        nombreUsuPanel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombreUsuPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuPanel.setText("Nombre de usuario");

        dniPanel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        dniPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dniPanel.setText("Dni");

        gmailPanel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        gmailPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gmailPanel.setText("Gmail");

        volverButton01.setText("Volver");
        volverButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton01ActionPerformed(evt);
            }
        });

        historialPagosButton.setText("Historial de Pagos");
        historialPagosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialPagosButtonActionPerformed(evt);
            }
        });

        obtenerGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerGmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuentaPanelLayout = new javax.swing.GroupLayout(cuentaPanel);
        cuentaPanel.setLayout(cuentaPanelLayout);
        cuentaPanelLayout.setHorizontalGroup(
            cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentaPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoLabel)
                    .addGroup(cuentaPanelLayout.createSequentialGroup()
                        .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cuentaPanelLayout.createSequentialGroup()
                                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(gmailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nombreUsuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addGroup(cuentaPanelLayout.createSequentialGroup()
                                .addComponent(historialPagosButton)
                                .addGap(57, 57, 57)))
                        .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(obtenerDni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(obtenerGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(obtenerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(volverButton01))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        cuentaPanelLayout.setVerticalGroup(
            cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuentaPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addGap(51, 51, 51)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtenerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gmailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtenerGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtenerDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(cuentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historialPagosButton)
                    .addComponent(volverButton01))
                .addGap(32, 32, 32))
        );

        mainPanel.add(cuentaPanel, "cuentaPanel");

        historialPagosPanel.setPreferredSize(new java.awt.Dimension(400, 277));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pago", "Fecha", "Datos"
            }
        ));
        pagosTable.setViewportView(jTable1);

        volverButton02.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        volverButton02.setText("Volver");
        volverButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton02ActionPerformed(evt);
            }
        });

        historialPagosLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        historialPagosLabel.setText("Historial De Pagos");

        javax.swing.GroupLayout historialPagosPanelLayout = new javax.swing.GroupLayout(historialPagosPanel);
        historialPagosPanel.setLayout(historialPagosPanelLayout);
        historialPagosPanelLayout.setHorizontalGroup(
            historialPagosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialPagosPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(historialPagosLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(historialPagosPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pagosTable, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton02)
                .addGap(19, 19, 19))
        );
        historialPagosPanelLayout.setVerticalGroup(
            historialPagosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historialPagosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(historialPagosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volverButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(historialPagosPanelLayout.createSequentialGroup()
                        .addComponent(historialPagosLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pagosTable, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );

        mainPanel.add(historialPagosPanel, "historialPagosPanel");

        catalogoLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        catalogoLabel.setText("Catálogo");

        componentesPcButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        componentesPcButton.setText("Componentes Pc");
        componentesPcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componentesPcButtonActionPerformed(evt);
            }
        });

        volverButton03.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        volverButton03.setText("Volver");
        volverButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton03ActionPerformed(evt);
            }
        });

        celularesButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        celularesButton.setText("Celulares");
        celularesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularesButtonActionPerformed(evt);
            }
        });

        almacenamientoButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        almacenamientoButton.setText("Almacenamiento");
        almacenamientoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenamientoButtonActionPerformed(evt);
            }
        });

        pcButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pcButton.setText("Pc");
        pcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout catalogoPanelLayout = new javax.swing.GroupLayout(catalogoPanel);
        catalogoPanel.setLayout(catalogoPanelLayout);
        catalogoPanelLayout.setHorizontalGroup(
            catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoPanelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(volverButton03)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogoPanelLayout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addGroup(catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(catalogoPanelLayout.createSequentialGroup()
                        .addComponent(almacenamientoButton)
                        .addGap(94, 94, 94)
                        .addComponent(pcButton))
                    .addGroup(catalogoPanelLayout.createSequentialGroup()
                        .addComponent(celularesButton)
                        .addGap(46, 46, 46)
                        .addComponent(componentesPcButton)))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(catalogoLabel)
                .addGap(197, 197, 197))
        );
        catalogoPanelLayout.setVerticalGroup(
            catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(catalogoLabel)
                .addGap(59, 59, 59)
                .addGroup(catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularesButton)
                    .addComponent(componentesPcButton))
                .addGap(32, 32, 32)
                .addGroup(catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almacenamientoButton)
                    .addComponent(pcButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(volverButton03)
                .addGap(34, 34, 34))
        );

        mainPanel.add(catalogoPanel, "catalogoPanel");

        tablaTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "ID", "Precio"
            }
        ));
        celularLista.setViewportView(tablaTelefonos);

        volverButton04.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        volverButton04.setText("Volver");
        volverButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton04ActionPerformed(evt);
            }
        });

        celularesLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        celularesLabel.setText("Celulares");

        añadirCestaButton01.setText("Añadir a cesta");
        añadirCestaButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirCestaButton01ActionPerformed(evt);
            }
        });

        celularBuscadorLabel.setText("Escriba el ID del producto que quiere añadir");

        javax.swing.GroupLayout celularesPanelLayout = new javax.swing.GroupLayout(celularesPanel);
        celularesPanel.setLayout(celularesPanelLayout);
        celularesPanelLayout.setHorizontalGroup(
            celularesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, celularesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(celularBuscadorLabel)
                .addGap(83, 83, 83))
            .addGroup(celularesPanelLayout.createSequentialGroup()
                .addGroup(celularesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(celularesPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(celularLista, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(celularesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(celularesPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(celularBuscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(celularesPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(añadirCestaButton01))))
                    .addGroup(celularesPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(celularesLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, celularesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(volverButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        celularesPanelLayout.setVerticalGroup(
            celularesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(celularesPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(celularesLabel)
                .addGap(27, 27, 27)
                .addComponent(celularBuscadorLabel)
                .addGap(18, 18, 18)
                .addGroup(celularesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(celularesPanelLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(celularBuscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(añadirCestaButton01)
                        .addGap(169, 169, 169))
                    .addGroup(celularesPanelLayout.createSequentialGroup()
                        .addComponent(celularLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(volverButton04)
                .addGap(23, 23, 23))
        );

        mainPanel.add(celularesPanel, "celularesPanel");

        tablaAlmacenamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "ID", "Precio"
            }
        ));
        almacenamientoLista.setViewportView(tablaAlmacenamiento);
        if (tablaAlmacenamiento.getColumnModel().getColumnCount() > 0) {
            tablaAlmacenamiento.getColumnModel().getColumn(0).setResizable(false);
        }

        volverButton06.setText("Volver");
        volverButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton06ActionPerformed(evt);
            }
        });

        almacenamientoLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        almacenamientoLabel.setText("Almacenamiento");

        buscadorAlmacenamientoLabel.setText("Introduzca el ID del producto que quiere añadir");

        añadirCestaButton02.setText("Añadir a cesta");

        javax.swing.GroupLayout almacenamientoPanelLayout = new javax.swing.GroupLayout(almacenamientoPanel);
        almacenamientoPanel.setLayout(almacenamientoPanelLayout);
        almacenamientoPanelLayout.setHorizontalGroup(
            almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenamientoPanelLayout.createSequentialGroup()
                .addGroup(almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenamientoPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(almacenamientoLabel))
                    .addGroup(almacenamientoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(almacenamientoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(almacenamientoBuscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(añadirCestaButton02))))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, almacenamientoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, almacenamientoPanelLayout.createSequentialGroup()
                        .addComponent(volverButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, almacenamientoPanelLayout.createSequentialGroup()
                        .addComponent(buscadorAlmacenamientoLabel)
                        .addGap(20, 20, 20))))
        );
        almacenamientoPanelLayout.setVerticalGroup(
            almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenamientoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(almacenamientoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(buscadorAlmacenamientoLabel)
                .addGap(18, 18, 18)
                .addGroup(almacenamientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(almacenamientoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(almacenamientoPanelLayout.createSequentialGroup()
                        .addComponent(almacenamientoBuscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(añadirCestaButton02)))
                .addGap(18, 18, 18)
                .addComponent(volverButton06)
                .addGap(21, 21, 21))
        );

        mainPanel.add(almacenamientoPanel, "almacenamientoPanel");

        tablaPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "ID", "Precio"
            }
        ));
        pcLista.setViewportView(tablaPC);

        volverButton07.setText("Volver");
        volverButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton07ActionPerformed(evt);
            }
        });

        pcLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pcLabel.setText("Ordenadores Personales");

        pcBuscadorLabel.setText("Introduzca el ID del producto que quiere añadir");

        añadirCestaButton03.setText("Añadir a cesta");

        javax.swing.GroupLayout pcPanelLayout = new javax.swing.GroupLayout(pcPanel);
        pcPanel.setLayout(pcPanelLayout);
        pcPanelLayout.setHorizontalGroup(
            pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pcPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pcBuscadorLabel)
                .addGap(25, 25, 25))
            .addGroup(pcPanelLayout.createSequentialGroup()
                .addGroup(pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pcPanelLayout.createSequentialGroup()
                        .addGroup(pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pcPanelLayout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(volverButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pcPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(pcLista, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(añadirCestaButton03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pcBuscadorText)))
                    .addGroup(pcPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(pcLabel)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pcPanelLayout.setVerticalGroup(
            pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcPanelLayout.createSequentialGroup()
                .addGroup(pcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pcPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pcLabel)
                        .addGap(39, 39, 39)
                        .addComponent(pcBuscadorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pcLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pcPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(pcBuscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(añadirCestaButton03)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(volverButton07)
                .addGap(15, 15, 15))
        );

        mainPanel.add(pcPanel, "pcPanel");

        tablaComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "ID", "Precio"
            }
        ));
        componentesPcLista.setViewportView(tablaComponentes);

        volverButton08.setText("Volver");
        volverButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton08ActionPerformed(evt);
            }
        });

        hardwareLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        hardwareLabel.setText("Hardware");

        hardwareBuscadorLabel.setText("Introduzca el ID del producto que quiere añadir");

        añadirCestaButton04.setText("Añadir a cesta");

        javax.swing.GroupLayout componentesPcPanelLayout = new javax.swing.GroupLayout(componentesPcPanel);
        componentesPcPanel.setLayout(componentesPcPanelLayout);
        componentesPcPanelLayout.setHorizontalGroup(
            componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentesPcPanelLayout.createSequentialGroup()
                .addGroup(componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volverButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(componentesPcPanelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(componentesPcLista, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(componentesPcPanelLayout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addComponent(hardwareLabel))))
                .addGap(49, 49, 49)
                .addGroup(componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hardwareBuscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añadirCestaButton04))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, componentesPcPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hardwareBuscadorLabel)
                .addGap(25, 25, 25))
        );
        componentesPcPanelLayout.setVerticalGroup(
            componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentesPcPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hardwareLabel)
                .addGroup(componentesPcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentesPcPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(hardwareBuscadorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(componentesPcLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(componentesPcPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(hardwareBuscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(añadirCestaButton04)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(volverButton08)
                .addGap(22, 22, 22))
        );

        mainPanel.add(componentesPcPanel, "componentesPcPanel");

        pedidosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id ", "Factura"
            }
        ));
        historialPedidosTable.setViewportView(pedidosTable);

        historialPedidosLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        historialPedidosLabel.setText("Historial De Pedidos");

        volverButton10.setText("Volver");
        volverButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout historialPedidosPanelLayout = new javax.swing.GroupLayout(historialPedidosPanel);
        historialPedidosPanel.setLayout(historialPedidosPanelLayout);
        historialPedidosPanelLayout.setHorizontalGroup(
            historialPedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialPedidosPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(historialPedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(historialPedidosPanelLayout.createSequentialGroup()
                        .addComponent(historialPedidosTable, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(volverButton10))
                    .addGroup(historialPedidosPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(historialPedidosLabel)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        historialPedidosPanelLayout.setVerticalGroup(
            historialPedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialPedidosPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(historialPedidosLabel)
                .addGap(18, 18, 18)
                .addGroup(historialPedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volverButton10)
                    .addComponent(historialPedidosTable, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        mainPanel.add(historialPedidosPanel, "historialPedidosPanel");

        cestaLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cestaLabel.setText("Cesta");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ));
        cestaTable.setViewportView(jTable2);

        volverButton11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        volverButton11.setText("Volver");
        volverButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cestaPanelLayout = new javax.swing.GroupLayout(cestaPanel);
        cestaPanel.setLayout(cestaPanelLayout);
        cestaPanelLayout.setHorizontalGroup(
            cestaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cestaPanelLayout.createSequentialGroup()
                .addGroup(cestaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cestaPanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(cestaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cestaPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cestaTable, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(volverButton11)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        cestaPanelLayout.setVerticalGroup(
            cestaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cestaPanelLayout.createSequentialGroup()
                .addGroup(cestaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cestaPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverButton11))
                    .addGroup(cestaPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cestaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cestaTable, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        mainPanel.add(cestaPanel, "cestaPanel");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Estado", "Información"
            }
        ));
        pedidoTable.setViewportView(jTable3);

        volverButton12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        volverButton12.setText("Volver");
        volverButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButton12ActionPerformed(evt);
            }
        });

        pedidosLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pedidosLabel.setText("Pedidos");

        javax.swing.GroupLayout pedidosPanelLayout = new javax.swing.GroupLayout(pedidosPanel);
        pedidosPanel.setLayout(pedidosPanelLayout);
        pedidosPanelLayout.setHorizontalGroup(
            pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedidosPanelLayout.createSequentialGroup()
                .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pedidosPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pedidoTable, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(volverButton12))
                    .addGroup(pedidosPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(pedidosLabel)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pedidosPanelLayout.setVerticalGroup(
            pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedidosPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pedidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volverButton12)
                    .addGroup(pedidosPanelLayout.createSequentialGroup()
                        .addComponent(pedidosLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pedidoTable, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        mainPanel.add(pedidosPanel, "pedidosPanel");

        accesoPrograma.setText("Acceso");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        accesoPrograma.add(login);

        crearCuenta.setText("Crear cuenta");
        crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaActionPerformed(evt);
            }
        });
        accesoPrograma.add(crearCuenta);

        jMenuItem1.setText("Main");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        accesoPrograma.add(jMenuItem1);

        jMenuBar1.add(accesoPrograma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        cambiarPanel("loginPanel");
    }//GEN-LAST:event_loginActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void dniUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniUsuarioActionPerformed

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        if (campoConteraseñaUsu.getText().equals(campoConfirmarContraseña.getText())) {

            if (crearUsuario()) {
                showMessage("Usuario creado :)");
                cambiarPanel("menuPanel");
            } else {
                showMessage("USUARIO YA EXISTE");
            }
        } else {
            showError("La contraseña no coincide");
        }
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    private void crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaActionPerformed
        cambiarPanel("crearCuentaPanel");


    }//GEN-LAST:event_crearCuentaActionPerformed

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed

        if (comprobarUsuario()) {
            cambiarPanel("menuPanel");
        }

    }//GEN-LAST:event_botonLoginActionPerformed

    private void componentesPcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componentesPcButtonActionPerformed
        cambiarPanel("componentesPcPanel");
        consultarComponentes();
    }//GEN-LAST:event_componentesPcButtonActionPerformed

    private void volverButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton04ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton04ActionPerformed

    private void volverButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton06ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton06ActionPerformed

    private void volverButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton07ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton07ActionPerformed

    private void volverButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton08ActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_volverButton08ActionPerformed

    private void volverButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton03ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_volverButton03ActionPerformed

    private void catalogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoButtonActionPerformed
        cambiarPanel("catalogoPanel");
    }//GEN-LAST:event_catalogoButtonActionPerformed

    private void historialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialButtonActionPerformed
        consultarPedidoUsuario();
        cambiarPanel("historialPedidosPanel");
    }//GEN-LAST:event_historialButtonActionPerformed

    private void cuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaButtonActionPerformed

        infoUsuario();
        cambiarPanel("cuentaPanel");
    }//GEN-LAST:event_cuentaButtonActionPerformed

    private void pedidosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosButtonActionPerformed
        cambiarPanel("pedidosPanel");
    }//GEN-LAST:event_pedidosButtonActionPerformed

    private void volverButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton02ActionPerformed
        cambiarPanel("cuentaPanel");


    }//GEN-LAST:event_volverButton02ActionPerformed

    private void celularesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularesButtonActionPerformed
        cambiarPanel("celularesPanel");
        consultarTelefono();
    }//GEN-LAST:event_celularesButtonActionPerformed

    private void almacenamientoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenamientoButtonActionPerformed

        cambiarPanel("almacenamientoPanel");

        consultarAlmacenamiento();

    }//GEN-LAST:event_almacenamientoButtonActionPerformed

    private void pcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcButtonActionPerformed
        cambiarPanel("pcPanel");
        consultarPc();
    }//GEN-LAST:event_pcButtonActionPerformed

    private void cestaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cestaButtonActionPerformed
        cambiarPanel("cestaPanel");
    }//GEN-LAST:event_cestaButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void volverButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton10ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_volverButton10ActionPerformed

    private void obtenerGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtenerGmailActionPerformed

    private void historialPagosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialPagosButtonActionPerformed
        cambiarPanel("historialPagosPanel");
    }//GEN-LAST:event_historialPagosButtonActionPerformed

    private void volverButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton01ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_volverButton01ActionPerformed

    private void volverButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton11ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_volverButton11ActionPerformed

    private void volverButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButton12ActionPerformed
        cambiarPanel("menuPanel");
    }//GEN-LAST:event_volverButton12ActionPerformed

    private void añadirCestaButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirCestaButton01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirCestaButton01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accesoPrograma;
    private javax.swing.JTextField almacenamientoBuscadorText;
    private javax.swing.JButton almacenamientoButton;
    private javax.swing.JLabel almacenamientoLabel;
    private javax.swing.JScrollPane almacenamientoLista;
    private javax.swing.JPanel almacenamientoPanel;
    private javax.swing.JButton añadirCestaButton01;
    private javax.swing.JButton añadirCestaButton02;
    private javax.swing.JButton añadirCestaButton03;
    private javax.swing.JButton añadirCestaButton04;
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton botonLogin;
    private javax.swing.JLabel buscadorAlmacenamientoLabel;
    private javax.swing.JPasswordField campoConfirmarContraseña;
    private javax.swing.JPasswordField campoConteraseñaUsu;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JButton catalogoButton;
    private javax.swing.JLabel catalogoLabel;
    private javax.swing.JPanel catalogoPanel;
    private javax.swing.JLabel celularBuscadorLabel;
    private javax.swing.JTextField celularBuscadorText;
    private javax.swing.JScrollPane celularLista;
    private javax.swing.JButton celularesButton;
    private javax.swing.JLabel celularesLabel;
    private javax.swing.JPanel celularesPanel;
    private javax.swing.JButton cestaButton;
    private javax.swing.JLabel cestaLabel;
    private javax.swing.JPanel cestaPanel;
    private javax.swing.JScrollPane cestaTable;
    private javax.swing.JButton componentesPcButton;
    private javax.swing.JScrollPane componentesPcLista;
    private javax.swing.JPanel componentesPcPanel;
    private javax.swing.JLabel confirmarContraseña;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel contraseñaUsu;
    private javax.swing.JLabel correoUsu;
    private javax.swing.JMenuItem crearCuenta;
    private javax.swing.JPanel crearCuentaPanel;
    private javax.swing.JButton cuentaButton;
    private javax.swing.JPanel cuentaPanel;
    private javax.swing.JLabel dniPanel;
    private javax.swing.JTextField dniUsuario;
    private javax.swing.JLabel gmailPanel;
    private javax.swing.JLabel hardwareBuscadorLabel;
    private javax.swing.JTextField hardwareBuscadorText;
    private javax.swing.JLabel hardwareLabel;
    private javax.swing.JButton historialButton;
    private javax.swing.JButton historialPagosButton;
    private javax.swing.JLabel historialPagosLabel;
    private javax.swing.JPanel historialPagosPanel;
    private javax.swing.JLabel historialPedidosLabel;
    private javax.swing.JPanel historialPedidosPanel;
    private javax.swing.JScrollPane historialPedidosTable;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JMenuItem login;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPrincipal;
    private javax.swing.JLabel nombreUsu;
    private javax.swing.JLabel nombreUsuPanel;
    private javax.swing.JTextField obtenerDni;
    private javax.swing.JTextField obtenerGmail;
    private javax.swing.JTextField obtenerNombre;
    private javax.swing.JScrollPane pagosTable;
    private javax.swing.JLabel pcBuscadorLabel;
    private javax.swing.JTextField pcBuscadorText;
    private javax.swing.JButton pcButton;
    private javax.swing.JLabel pcLabel;
    private javax.swing.JScrollPane pcLista;
    private javax.swing.JPanel pcPanel;
    private javax.swing.JScrollPane pedidoTable;
    private javax.swing.JButton pedidosButton;
    private javax.swing.JLabel pedidosLabel;
    private javax.swing.JPanel pedidosPanel;
    private javax.swing.JTable pedidosTable;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JTable tablaAlmacenamiento;
    private javax.swing.JTable tablaComponentes;
    private javax.swing.JTable tablaPC;
    private javax.swing.JTable tablaTelefonos;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton volverButton01;
    private javax.swing.JButton volverButton02;
    private javax.swing.JButton volverButton03;
    private javax.swing.JButton volverButton04;
    private javax.swing.JButton volverButton06;
    private javax.swing.JButton volverButton07;
    private javax.swing.JButton volverButton08;
    private javax.swing.JButton volverButton10;
    private javax.swing.JButton volverButton11;
    private javax.swing.JButton volverButton12;
    // End of variables declaration//GEN-END:variables
}
